#!/bin/sh
. /etc/profile
command="cd $PWD && /usr/local/bin/composer.phar --no-cache $@"
if [ -n $RUN_USER ]; then
    composerHome=/var/www/.composer
    command="export COMPOSER_HOME=$composerHome && $command"
    if [ ! -d $composerHome ]; then
        mkdir -p $composerHome
        chown $RUN_USER:$RUN_USER $composerHome
    fi
    if [ ! -f $composerHome/config.json ]; then
        cp /root/.composer/config.json $composerHome/config.json
        chown $RUN_USER:$RUN_USER $composerHome/config.json
    fi
    su - $RUN_USER -c "$command"
else
    /bin/sh -c "$command"
fi
