#!/bin/sh
if [ $(id -u) -eq 0 ]; then
    export RUN_USER="root"
    if [ $UID -gt 0 ] && [ $GID -gt 0 ]; then
        export RUN_USER=$(getent passwd "$UID" | cut -d: -f1)
        if [ -z $RUN_USER ]; then
            export RUN_USER="container"
        fi
        # if the specify user not exists, create it
        if [ -z "$(cat /etc/passwd | grep :$UID:$GID:)" ]; then
            # delete user and group if exists
            (/usr/sbin/deluser $RUN_USER > /dev/null)
            (/usr/sbin/delgroup $RUN_USER > /dev/null)
            # create user
            /usr/sbin/addgroup -g $GID $RUN_USER
            /usr/sbin/adduser --disabled-password --gecos "" --home /var/www --ingroup container --no-create-home --uid $UID $RUN_USER
        fi
    fi
    # export the container user
    if [ -z "$(cat /etc/profile | grep RUN_USER=$RUN_USER)" ]; then
        echo "export RUN_USER=$RUN_USER" >> /etc/profile
    fi
    # start supervisord
    if [ $QUEUE_NUM_PROCS -gt 0 ]; then
        (/usr/bin/supervisord -c /usr/local/etc/supervisor.conf > /dev/null) &
        echo "supervisord started"
    fi
    # start supercronic
    if [ `expr match "$SCHEDULE" "[O|o][N|n]$"` -ne 0 ]; then
        (/usr/local/bin/supercronic /usr/local/etc/crontab.txt > /dev/null) &
        echo "supercronic started"
    fi
    # replace fpm user
    if [ ! -f /usr/local/etc/php-fpm.d/www.conf.original ]; then
        /bin/cp -f /usr/local/etc/php-fpm.d/www.conf /usr/local/etc/php-fpm.d/www.conf.original
        /bin/sed -i "s/user = www-data/user = $RUN_USER/g" /usr/local/etc/php-fpm.d/www.conf
        /bin/sed -i "s/group = www-data/user = $RUN_USER/g" /usr/local/etc/php-fpm.d/www.conf
        echo "set fpm user: $RUN_USER"
    fi
else
    echo "You should specify the execution user by '-e UID=1000' and '-e GID=1000'."
    exit 1
fi

